---
title: "bad-graph"
format: html
---

```{r}
# General use packages:
library(tidyverse)
library(here)
library(janitor)

# Specifically for plots:
library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)
library(beeswarm)
library(wesanderson)
library(RColorBrewer)
library(ggpubr)
library(jpeg)

# And for another dataset we'll explore:
library(gapminder)

# Spatial
library(sf)
library(radarchart)
```
```{r}
space_launch <- read_csv(here("data", "space_launches.csv"))
```

```{r}
space_count <- space_launch %>% 
  count(agency)
img <- jpeg::readJPEG("img.jpeg")

bad_plot <- ggplot(space_count, aes(agency, n)) +
  background_image(img) +
  geom_segment(aes(x=agency, xend=agency, y=0, yend= n, color = "agency"),show.legend = FALSE, linewidth=1, linetype="dotdash") +
  geom_point(aes(color = agency), show.legend = FALSE) +
  #scale_color_manual(palette = "yellow") +
  theme(axis.text.x = element_text(size = 10, family = "Papyrus", angle = 50),
        axis.title.x = element_text(size = 20, family = "Papyrus", angle = 175),
        axis.text.y = element_text(size = 10, family = "Papyrus", angle = 75),
        axis.title.y = element_text(size = 20, family = "Papyrus", angle = 175),
        panel.background = element_rect(fill = "orange"),
        title = element_text(size = 30, family = "Papyrus")) +
  labs(title = "How Bad Can I Be?")

bad_plot
ggsave("bad_plot.jpeg", bad_plot)
```
```{r}
space_group <- space_launch %>% 
  group_by(launch_year, agency, category, agency_type) %>% 
  summarize(launch_count = n(), na.rm = TRUE) %>% 
    drop_na(agency)

better_plot <- ggplot(space_group, aes(launch_year, launch_count, fill = agency_type)) +
  geom_col() +
  labs(title = "Space Launches per Year by Agencies",
       x = "Year",
       y = "Number of Space Launches",
       fill = "Agency Type") +
  scale_fill_manual(values = c("darkgreen", "lightpink", "lightblue"))+
  facet_wrap(~category, labeller = 
               as_labeller(c('F' ="Failure", 'O' = "Success"))) +
    theme_classic()
  #scale_color_manual(values = c("lightpink", "darkblue", "gray"))
  
ggsave("better_plot.jpeg", better_plot)
```
```{r}
sf_emissions <- read_csv(here("data", "San_Francisco_Communitywide_Greenhouse_Gas_Inventory.csv"))
```

```{r}
annual_sf_sector <- sf_emissions %>% 
  group_by(Calendar_Year, Sector_General) %>% 
  summarise(total_co2 = sum(Emissions_mtCO2e, na.rm = TRUE))

annual_sf_commodity <- sf_emissions %>% 
  group_by(Calendar_Year, Commodity_Type) %>% 
  summarise(total_co2 = sum(Emissions_mtCO2e, na.rm = TRUE))
  
```

```{r}
sf_subset <- sf_emissions %>% 
  filter(Calendar_Year >= 2005,
         str_detect(Sector_Detail2, pattern = "PG&E")) %>% 
  select("Calendar_Year", "Sector_Detail2", "Emissions_mtCO2e")
  
```

```{r}
ggplot(annual_sf_sector, aes(Calendar_Year, total_co2/100000, color = Sector_General))  +
  geom_line() +
  labs(x = "Year",
       y = "CO2 Emission (100,000 metric tons",
       color = "Sector") +
  scale_color_paletteer_d("nationalparkcolors::Acadia") +
  theme_classic()

```

